#!/bin/bash

extract() {
    pybabel extract -F babel.cfg -o messages.pot .
}

init() {
    pybabel init -i messages.pot -d translations -l "$1"
}

update() {
    pybabel update -i messages.pot -d translations
}

compile() {
    pybabel compile -d translations
}

rebuild() {
    extract
    update
}
