#!/bin/bash

serve() {
  .venv/bin/python app.py
}

deploy() {
  lift deploy
}

format() {
  ruff format .
  prettier --write "**/*.{css,js}"
  prettier --write "**/*.json"
  djlint . --reformat
  markdownlint --fix "**/*.md" || true
}
